web: gunicorn server:app -k uvicorn.workers.UvicornWorker -w 3 --timeout 120 --bind 0.0.0.0:$PORT --access-logfile - --error-logfile - --max-requests 1000 --max-requests-jitter 100
worker: rq worker --url $REDIS_URL default
